import Head from "next/head";
import { useTheme } from 'next-themes';
import Layout from "../components/Layout";

const dummyData = [
  { name: "name1", desc: "desc1" },
  { name: "name2", desc: "desc2" },
  { name: "name3", desc: "desc3" },
  { name: "name4", desc: "desc4" },
];

export default function Grid() {
  const { theme, setTheme } = useTheme();

  const changeTheme = (param) => {
    setTheme(param)
    localStorage.setItem("mode", param);
  };

  return (
    <div>
      <Head>
        <title>App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="p-5">
          <div className="mb-4">
            <input
              type="radio"
              name="mode"
              onClick={() => changeTheme("light")}
            />{" "}
            Light
            <input
              type="radio"
              name="mode"
              className="ml-3"
              onClick={() => changeTheme("dark")}
            />{" "}
            Dark
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2">
            {dummyData.map((obj) => (
              <div
                key={obj.name}
                className="border-2 border-primary rounded-md p-3"
              >
                <h2 className="text-center">{obj.name}</h2>
                <div className="text-center">value:</div> 
                <h3 className="text-center dark:text-yellow-500">{obj.desc}</h3>
              </div>
            ))}
          </div>
        </div>
      </Layout>
    </div>
  );
}
