import Layout from "../components/Layout";
import Head from "next/head";

const dummyData = [
  { name: "name1", desc: "desc1" },
  { name: "name2", desc: "desc2" },
  { name: "name3", desc: "desc3" },
  { name: "name4", desc: "desc4" },
  { name: "name5", desc: "desc5" },
  { name: "name6", desc: "desc6" },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="px-2 p-5 bg-white tablet:bg-gray-400">
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2">
            {dummyData.map((obj) => (
              <div
                key={obj.name}
                className="border-2 border-primary rounded-md p-3 box"
              >
                <h2 className="text-center">{obj.name}</h2>
                <div className="text-center">{obj.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </Layout>
    </div>
  );
}
